name: gpm
version: 0.2.3
description:
  An easy command-line tool for testing and building monorepos (multi-package repositories).
homepage: https://github.com/dint-dev/gpm
executables:
  gpm:

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  args: ^1.4.0
  boolean_selector: ^2.0.0
  meta: ^1.1.0
  package_config: ^1.9.3
  yaml: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.10.0
